apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp
  namespace: argocd
spec:
  description: 3차시 실습 앱 프로젝트 (prd)
  sourceRepos:
    - REPO_URL_PLACEHOLDER
  destinations:
    - namespace: 'myapp-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
