apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glm-serving
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secretprovider.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - hpa.yaml
